### PR TITLE
Add Hodor to names.csv

### PR DESCRIPTION
**Pull request by lukasz-madon**

### CODE REVIEW

**Comment by appointmind** [comment]
As you can see in the list there are only characters that actually have last name. Thanks for the suggestion, though.

**Comment by ogregoire** [comment]
His name is obviously Hodor Hodor! Just ask him ;)

**Comment by appointmind** [comment]
:-) The thing is that I couldn't get through "A Game of Thrones" and have ignored "A Song of Ice and Fire" and the TV series. So, no Game of Thrones characters in my list.

**Comment by lukasz-madon** [comment]
Walder Hodor maybe?

http://awoiaf.westeros.org/index.php/Hodor

**Comment by appointmind** [comment]
From the page: "[...] until enlightened by Old Nan, his great-grandmother, that his real name is Walder."

Still only one name. ;-)

**Pull request closed without merging**
