### PR TITLE
Add header row

### PR DESCRIPTION
**Pull request by jayanderson**

### CODE REVIEW

**Comment by androm3da** [comment]
phew, thank goodness, my OCD was kicking in. :)

**Comment by appointmind** [comment]
Thanks for your contribution, but the file is supposed to be machine readable and doesn't really need a header row.

**Comment by christianbundy** [comment]
This should've been merged. CSV files are machine-readable, and the header row is often expected ([although it is technically optional](https://tools.ietf.org/html/rfc4180#section-2)). For example, take a look at [how Github renders the first row of the table](https://github.com/appointmind/fakenames/blob/master/names.csv).

**Comment by appointmind** [comment]
The script I'm using with this file doesn't expect a header row and the Github web frontend is not the targeted medium. :-)

**Pull request closed without merging**
